version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm start
            npm run build
            npm run prettier
            
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Build back-end
          command:
            npm install
            npm start
            npm run start:dev
            npm run webpack
            npm run start:hmr
            npm run start:prod
            npm run test
            npm run test:e2e
            npm run test:cov
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflow:
  ExecuteJobs:
    jobs:
      - build-frontend
      - build-frontend